package com.mycompany.proyecto.Math_Socket_Project_1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alero
 */
public class GUIPregunta extends javax.swing.JFrame {
    private ActionListenerPregunta pregunta;

    /**
     * Creates new form GUIPregunta
     */
    public GUIPregunta() {
        initComponents();
        this.pregunta = new ActionListenerPregunta(this);
        panelPregunta2.setActionListenerPregunta(pregunta);
        panelPregunta2.escuchar(pregunta);
        
    }
    
    /**
     * Cambia el string del label
     * @param pregunta string de la pregunta que se genero
     */
    public void setPregunta(String pregunta){
        this.panelPregunta2.pregunta.setText(pregunta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPregunta2 = new com.mycompany.proyecto.Math_Socket_Project_1.PanelPregunta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(panelPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(panelPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.proyecto.Math_Socket_Project_1.PanelPregunta panelPregunta2;
    // End of variables declaration//GEN-END:variables
}
