/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto.Math_Socket_Project_1;

import java.awt.Graphics;

/**
 *
 * @author alero
 */
public class GUITablero extends javax.swing.JFrame {
    
    private ActionListenerTablero tablero;

    /**
     * Metodo constructor
     */
    public GUITablero() {
        initComponents();
        this.tablero = new ActionListenerTablero(panelTablero1);
        
        panelTablero1.setActionListenerTablero(tablero);
        panelBoton2.setActionListenerTablero(tablero);
        panelBoton2.escuchar(tablero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero1 = new com.mycompany.proyecto.Math_Socket_Project_1.PanelTablero();
        panelBoton2 = new com.mycompany.proyecto.Math_Socket_Project_1.PanelBoton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelTablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 557, 285));
        getContentPane().add(panelBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.proyecto.Math_Socket_Project_1.PanelBoton panelBoton2;
    private com.mycompany.proyecto.Math_Socket_Project_1.PanelTablero panelTablero1;
    // End of variables declaration//GEN-END:variables
}
