/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto.Math_Socket_Project_1;

import java.awt.event.ActionListener;

/**
 *
 * @author alero
 */
public class PanelBoton extends javax.swing.JPanel {

    private ActionListenerTablero tablero;

    /**
     * Creates new form PanelBoton
     */
    public PanelBoton() {
        initComponents();
    }

    /**
     * Asina un ActionListenerTablero al tablero de la clase
     * @param tablero ActionListenerTablero que se va a asignar
     */
    public void setActionListenerTablero(ActionListenerTablero tablero) {
        this.tablero = tablero;
    }

    /**
     * Agrega un ActionListener a un boton
     * @param e ActionListener que va a agregar
     */
    public void escuchar(ActionListener e) {
        btnDice.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDice = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDice.setText("Roll Dice");
        add(btnDice, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 121, 39));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDice;
    // End of variables declaration//GEN-END:variables
}
