/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto.Math_Socket_Project_1;

import java.awt.Graphics;
import java.awt.event.ActionListener;

/**
 *
 * @author alero
 */
public class PanelTablero extends javax.swing.JPanel {
    
    private ActionListenerTablero tablero;
    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
    }
    
    /**
     * Asigna un ActionListener al tablero
     */
    public void setActionListenerTablero(ActionListenerTablero tablero){
        this.tablero = tablero;
    }

    /**
     * Llama las funciones para dibujar el tablero y los jugadores
     * @param g 
     */
    public void paint(Graphics g) {
        super.paintComponent(g);
        this.tablero.dibujar(g);
        this.tablero.paintPlayer(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
